# Jetpack release notes: https://developer.android.com/jetpack/androidx/versions/all-channel
# Android studio release notes: https://androidstudio.googleblog.com/
# AGP releases: https://developer.android.com/reference/tools/gradle-api
# AGP x Gradle Compatibility https://developer.android.com/build/releases/gradle-plugin#updating-gradle
# AGP x AS Compatibility: https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility
# Compose x Kotlin Compatibility: https://developer.android.com/jetpack/androidx/releases/compose-kotlin
# KSP x Kotlin: https://github.com/google/ksp/releases

[versions]
compileSdk = "36"
mediarouter = "1.7.0"
minSdk = "26"
playServicesCastFramework = "22.0.0"
targetSdk = "36"
java = "17"

androidGradlePlugin = "8.13.0"
androidMaterial = "1.12.0"
androidPlayServicesAds = "23.6.0"
androidxActitivty = "1.9.3"
androidxAppcompat = "1.7.0"
androidxBaselineProfile = "1.3.3"
androidxComposeBom = "2025.03.00"
androidxCore = "1.15.0"
androidxCoreSplashScreen = "1.0.1"
androidxDataStore = "1.1.1"
androidxLifecycle = "2.8.7"
androidxMacrobenchmark = "1.2.4"
androidxMedia3 = "1.5.1"
androidxNavigationCompose = "2.8.4"
androidxProfileInstaller = "1.3.1"
androidxStartupRuntime = "1.1.1"
androidxTest = "1.5.0"
androidxTestExtTruth = "1.5.0"
androidxTestJunit = "1.1.5"
androidxTestRunner = "1.5.2"
androidxTestUiAnimator = "2.3.0"
androidxWearNavigationCompose = "1.4.0"
androidxWearToolingPreview = "1.0.0"
coil = "2.7.0"
compose-wear = "1.4.0"
composeMarkdown = "0.5.2"
desugarJdk = "2.1.5"
detekt = "1.23.8"
detektRulesCompose = "0.4.27"
dokka = "2.1.0"
easyLauncher = "6.4.0"
espressoCore = "3.6.1"
firebaseAppDistributionGradlePlugin = "5.0.0"
firebaseBom = "33.7.0"
firebaseCrashlyticsGradlePlugin = "3.0.2"
firebasePerfGradlePlugin = "1.4.2"
gmsGoogleServicesGradlePlugin = "4.4.2"
gradleVersionPlugin = "0.50.0"
horologist = "0.6.18"
junit = "4.13.2"
junitVersion = "1.2.1"
koin = "4.0.2"
kotlin = "2.2.20"
kotlin-android = "2.2.20"
kotlinxCollectionsImmutable = "0.3.7"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
ksp = "2.2.20-2.0.4" # Must be compatible with ktorfit
ktor = "3.3.1"
ktorfit = "2.6.4"
ktlint = "0.50.0"
leakcanary = "2.14"
lint = "31.12.2"
kotoxBom = "2025.10.15"
okhttp = "4.12.0"
placeholder = "0.33.0-alpha"
prettyTime = "5.0.4.Final"
room = "2.6.1"
spotless = "8.0.0"
systemUi = "0.32.0"
tiles = "1.4.1"
timber = "5.0.1"
watchface-complications = "1.2.1"
core = "1.15.0"
media3Cast = "1.5.1"


[plugins]
buildLogic-kotlin-library = { id = "kotox.crypto.kotlin.library" }
buildLogic-android-test = { id = "kotox.crypto.android.test" }
buildLogic-android-room = { id = "kotox.crypto.android.room" }
buildLogic-android-ktor = { id = "kotox.crypto.sdk.kmp.ktor" }
buildLogic-sdk-android-library = { id = "kotox.crypto.sdk.android.library" }
buildLogic-sdk-android-ui-library = { id = "kotox.crypto.sdk.android.ui.library" }
buildLogic-sdk-android-application = { id = "kotox.crypto.sdk.android.application" }
buildLogic-dokka = { id = "kotox.crypto.sdk.dokka" }
buildLogic-sdk-version-read = { id = "kotox.crypto.sdk.version.read" }
buildLogic-sdk-version-update = { id = "kotox.crypto.sdk.version.update" }

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
androidx-baselineProfile = { id = "androidx.baselineprofile", version.ref = "androidxBaselineProfile" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
easyLauncher = { id = "com.starter.easylauncher", version.ref = "easyLauncher" }
firebase-appDistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistributionGradlePlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradlePlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfGradlePlugin" }
gms-googleServices = { id = "com.google.gms.google-services", version.ref = "gmsGoogleServicesGradlePlugin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }
android-material = { module = "com.google.android.material:material", version.ref = "androidMaterial" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActitivty" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidxMacrobenchmark" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }# remove as soon as ModalBottomSheet appears in material3
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-material-icons = { module = "androidx.compose.material:material-icons-extended" }

androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

androidx-media-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "androidxMedia3" }
androidx-media-exoplayer-ima = { module = "androidx.media3:media3-exoplayer-ima", version.ref = "androidxMedia3" }
androidx-media-ui = { module = "androidx.media3:media3-ui", version.ref = "androidxMedia3" }

android-playServices-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "androidPlayServicesAds" }

androidx-mediarouter = { module = "androidx.mediarouter:mediarouter", version.ref = "mediarouter" }
androidx-wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "compose-wear" }
androidx-wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "compose-wear" }
androidx-wear-tooling-preview = { module = "androidx.wear:wear-tooling-preview", version.ref = "androidxWearToolingPreview" }
androidx-wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "tiles" }
androidx-wear-tiles-material = { module = "androidx.wear.tiles:tiles-material", version.ref = "tiles" }
androidx-wear-complications = { module = "androidx.wear.watchface:watchface-complications-data-source-ktx", version.ref = "watchface-complications" }
androidx-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidxWearNavigationCompose" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashScreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
androidx-profileInstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidxProfileInstaller" }

androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartupRuntime" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestJunit" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidxTestExtTruth" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-uianimator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxTestUiAnimator" }

android-horologist-composeTools = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist" }
android-horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist" }
android-horologist-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
android-horologist-audioUi = { module = "com.google.android.horologist:horologist-audio-ui", version.ref = "horologist" }

coil-kt = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-kt-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-perf = { module = "com.google.firebase:firebase-perf-ktx" }
firebase-remoteconfig = { module = "com.google.firebase:firebase-config-ktx" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-instrumentation = { module = "com.squareup.leakcanary:leakcanary-android-instrumentation", version.ref = "leakcanary" }

lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }

kotox-crypto-bom = { module = "cz.kotox.crypto.sdk:bom", version.ref = "kotoxBom" }
kotox-crypto-common = { module = "cz.kotox.crypto.sdk:common" }
kotox-crypto-coindata = { module = "cz.kotox.crypto.sdk:coindata" }

network-ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
network-ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
network-ktor-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
network-ktor-wss = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
network-ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
network-ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
network-ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
network-ktor-httpSend = { module = "io.ktor:client-http-send", version.ref = "ktor" }
network-ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
network-ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
network-ktor-plugins = { module = "io.ktor:ktor-client-plugins", version.ref = "ktor" }
network-ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
network-ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }
network-ktorfit-converters-call = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-call", version.ref = "ktorfit" }
network-ktorfit-converters-flow = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-flow", version.ref = "ktorfit" }
network-ktorfit-converters-response = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-response", version.ref = "ktorfit" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

placeholder = { module = "com.google.accompanist:accompanist-placeholder-material3", version.ref = "placeholder" }
play-services-cast-framework = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "playServicesCastFramework" }
pretty-time = { module = "org.ocpsoft.prettytime:prettytime", version.ref = "prettyTime" }


room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

system-ui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "systemUi" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Detekt checks
detektRules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektRulesCompose" }

dokka-versioning = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }

# Dependencies of the included build-logic
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-media3-cast = { group = "androidx.media3", name = "media3-cast", version.ref = "media3Cast" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

[bundles]
compose = [
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-preview",
    "androidx-compose-ui-tooling",
]

kotlin-android = [
    "kotlin-stdlib",
    "kotlin-stdlib-jdk8",
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-core",
]

test-unit = [
    "junit",
    "androidx-test-core",
    "androidx-test-junit",
    "androidx-test-truth",
    "kotlin-test"
]

test-android = [
    "androidx-test-runner",
    "androidx-test-core",
    "androidx-test-junit",
    "kotlinx-coroutines-test"

]
